on:
  workflow_call:
    inputs:
      project-folder:
        required: true
        type: string
      upm-branch:
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout release
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - name: Fetch branch
        run: git fetch origin ${{ inputs.upm-branch }}:${{ inputs.upm-branch }} || true
      - name: Create upm branch if it does not yet exist
        run: git branch ${{ inputs.upm-branch }} || true
      - name: Move to upm branch without changing working copy
        run: |
          git checkout --detach
          git reset --soft ${{ inputs.upm-branch }}
          git checkout ${{ inputs.upm-branch }}
      - name: Remove everything except for our project
        run: |
          git rm -rf .
          git checkout --detach
          git reset --soft ${{ github.ref }}
          git checkout ${{ github.ref }}
          git checkout HEAD -- ${{ inputs.project-folder }}
          git checkout --detach
          git reset --soft ${{ inputs.upm-branch }}
          git checkout ${{ inputs.upm-branch }}
      - name: Create UPM package for our project
        run: |
          git mv ${{ inputs.project-folder }}/Assets/* .
          git rm -rf ${{ inputs.project-folder }}
          rm -rf ${{ inputs.project-folder }}
          git rm -f Readme.md
          git rm -f Readme.md.meta
          git mv Samples Samples~
          git rm -f Samples.meta
          ls -R | grep ":$" | sed -e 's/:$//' -e 's/[^-][^\/]*\//  /g' -e 's/^/   /'
      - name: Config user name
        run: git config --global user.name "github-actions[bot]"
      - name: Config user email
        run: git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Add
        run: git add *
      - name: Commit
        run: git commit -m "Add upm package for ${GITHUB_REF#refs/*/}"
      - name: Tag
        run: git tag -a upm-${GITHUB_REF#refs/*/} -m ""
      - name: Push
        run: git push --follow-tags --set-upstream origin ${{ inputs.upm-branch }}
