name: Update upm-ubiq branch on release
on:
  push:
    tags: [ 'ubiq-v*.*.*' ]
jobs:
  build-upm:
    uses: ./.github/workflows/build-upm-from-project-folder.yml
    with:
      project-folder: Unity
      upm-branch: upm-ubiq